define(["qlik","jquery","text!./style.css"],function(qlik,$,cssContent){$("<style>").html(cssContent).appendTo("head");function returnTotals(dimension,total,positionTotal,measureLabel,padding){var totalHtml='\n                <div class="chart-ghsl-total" style="border-'+(positionTotal?"bottom":"top")+": 2px dashed #EFEFF3;margin:"+(!positionTotal?padding/2:padding)+'vh 0px;">\n                    <div>\n                        <span>Total '+dimension+" - "+total+"</span>\n                    </div>\n                    <div>\n                        <span>"+
measureLabel+"</span>\n                    </div>\n                </div>\n                ";return totalHtml}function returnMaxValue(data){var maxValue=0;data.map(function(item){if(item[1].qNum>maxValue)maxValue=item[1].qNum});return maxValue}return{initialProperties:{qHyperCubeDef:{qDimensions:[],qMeasures:[],qInitialDataFetch:[{qWidth:10,qHeight:50}]}},definition:{type:"items",component:"accordion",items:{dimensions:{uses:"dimensions",min:1,max:1,items:{colorDimension:{type:"string",label:"Cor da Barra",
exoression:"always",ref:"qAttributeExpressions.0.qExpression",component:"expression",defaultValue:"ColorMix1( (rank(column(1))/(noofrows(TOTAL))), rgb(8, 34, 24), rgb(32, 228, 156))"}}},measures:{uses:"measures",min:1,max:1},sorting:{uses:"sorting"},settings:{uses:"settings",items:{myPropertiesTotal:{type:"items",label:"Total",items:{showTotal:{ref:"myProperties.showTotal",label:"Mostrar total",type:"boolean",defaultValue:true},totalPosition:{ref:"myProperties.totalPosition",label:"Posi\u00e7\u00e3o do total",
component:"buttongroup",options:[{value:"true",label:"Superior"},{value:"false",label:"Inferior"}],defaultValue:"true"}}},myPropertiesBar:{type:"items",label:"Barra",items:{showRadius:{ref:"myProperties.showRadius",label:"Arredondar borda da barra",type:"boolean",defaultValue:true},heightBar:{ref:"myProperties.heightBar",label:"Altura da barra (vh)",type:"string",defaultValue:"2"},paddingLine:{ref:"myProperties.paddingLine",label:"Margem da Linha(vh)",type:"string",defaultValue:"1"},showPercent:{ref:"myProperties.showPercent",
label:"Mostrar percentual (total)",type:"boolean",defaultValue:true},percentColor:{ref:"myProperties.percentColor",label:"Cor do percentual",type:"string",expression:"always",defaultValue:"#FFFFFF"}}}}}}},snapshot:{canTakeSnapshot:true},paint:function($element,dataR){var app=qlik.currApp();var data=dataR.qHyperCube.qDataPages[0].qMatrix;var dataTotals=dataR.qHyperCube.qGrandTotalRow;var dataDimensionsInfo=dataR.qHyperCube.qDimensionInfo;var dataMeasuresInfo=dataR.qHyperCube.qMeasureInfo;var myProperties=
dataR.myProperties;var valueTotal=dataTotals[0].qText;var valueTotalCalc=dataTotals[0].qNum;var dimensionName=dataDimensionsInfo[0].qFallbackTitle;var dimensionField=dataDimensionsInfo[0].qGroupFieldDefs[0];var measureLabel=dataMeasuresInfo[0].qFallbackTitle;var totalPosition=myProperties.totalPosition==="true";var showTotal=myProperties.showTotal;var maxValue=returnMaxValue(data);var percentColor=myProperties.percentColor;var heightBar=myProperties.heightBar;var paddingLine=myProperties.paddingLine;
var showRadius=myProperties.showRadius;var showPercent=myProperties.showPercent;var animateBar=myProperties.animateBar;var html='<div id="'+dataR.qInfo.qId+'" class="chart-ghsl">';if(showTotal&&totalPosition)html+=returnTotals(dimensionName,valueTotal,totalPosition,measureLabel,paddingLine);data.map(function(item,idBar){var barSize=item[1].qNum/maxValue*100;var barPercent=item[1].qNum/valueTotalCalc*100;var barColorQlik=item[0].qAttrExps.qValues[0].qText?item[0].qAttrExps.qValues[0].qText:"#202125";
var barColor=item[0].qAttrExps.qValues[0].qText?item[0].qAttrExps.qValues[0].qText:barColorQlik;html+='\n            <div data="'+item[0].qText+'" class="masterItem-ghsl masterItem-ghsl-'+dataR.qInfo.qId+'" style="margin-bottom: '+paddingLine+'vh;">\n                <div class="item-ghsl"">\n                    <div class="item-ghsl-top">\n                        <div><span id="item-ghsl-dim-'+dataR.qInfo.qId+"-"+idBar+'">'+item[0].qText+'</span></div>\n                        <div class="item-ghsl-top-right"><span>'+
item[1].qText+'</span></div>\n                    </div>\n                    <div>\n                        <div class="item-ghsl-bottom">\n                            <div id="item-ghsl-bottom-bar-'+dataR.qInfo.qId+"-"+idBar+'" class="item-ghsl-bottom-bar" style="background: '+barColor.replace("ARGB","RGB").replace("255,","")+"; width: "+(animateBar?"0px":barSize.toString()+"%")+"; height:"+heightBar+"vh; border-top-right-radius: "+(showRadius?heightBar/2:0)+"vh;border-bottom-right-radius: "+(showRadius?
heightBar/2:0)+'vh; ">\n                                '+(barSize>=10?'<p style="color: '+(barSize<10?barColor.replace("ARGB","RGB").replace("255,",""):percentColor)+"; height: "+heightBar*.8+"vh; font-size: "+heightBar*.8+"vh; line-height: "+heightBar*.8+'vh;">'+(showPercent?barPercent.toFixed(2).toString()+"%":"")+"</p>":"")+"\n                            </div>\n                            "+(barSize<10?'<div><p style="color: '+(barSize<10?barColor.replace("ARGB","RGB").replace("255,",""):percentColor)+
"; height: "+heightBar*.8+"vh; font-size: "+heightBar*.8+"vh; line-height: "+heightBar*.8+'vh;">'+(showPercent?barPercent.toFixed(2).toString()+"%":"")+"</p></div>":"")+"\n                        </div>\n                    </div>\n                </div>\n            </div>\n        "});if(showTotal&&!totalPosition)html+=returnTotals(dimensionName,valueTotal,totalPosition,measureLabel,paddingLine);html+="</div>";$element.html(html);if(qlik.navigation.getMode()!=="edit"){var bars=document.getElementsByClassName("masterItem-ghsl-"+
dataR.qInfo.qId);for(var x=0;x<bars.length;x++)bars[x].onclick=function(e){e.preventDefault();app.field(dimensionField).selectMatch(this.getAttribute("data"),true)}}}}});